list.of.packages <- c(
  "dplyr","ggplot2","psych",
  "knitr","likert", "scales",
  "ggrepel", "stringr", "data.table",
  "gridExtra" , "reshape2"
)

new.packages <- list.of.packages[!(list.of.packages %in% installed.packages()[,"Package"])]
if(length(new.packages)) install.packages(new.packages, dependencies = TRUE)
lapply(list.of.packages,require,character.only=TRUE)

firstup <- function(x) {
  substr(x, 1, 1) <- toupper(substr(x, 1, 1))
  x
}

survey_identifiers <- function(){
  keyval_survey <- list(
    "timestamp" =   "Timestamp",
    "demo_gender"   =   "Gender",
    "demo_role" =   "Which of these options is most suitable to describe your current primary role?",
    "xp_artif_share"    =   "How would you rate your experience in artifact development and sharing in MDE research projects?",
    "xp_artif_reuse"    =   "How would you rate your experience in reusing artifacts from MDE research projects?",
    "xp_artif_submit"   =   "Have you ever submitted an artifact for evaluation to some conference, workshop, or journal?",
    "auth_you_contact"  =   "Have you ever contacted other researchers for help on reusing their artifacts?",
    "auth_contact_you"  =   "Have you ever been contacted by other researchers interested to reuse some artifact you shared?",
    "challenges"    =   "Which challenges have you encountered during the sharing and use of artifacts in MDE research projects?",
    "what_q1_p1"    =   "1.1) What is it all about? [its name]",
    "what_q1_p2"    =   "1.1) What is it all about? [the context of its development (e.g., domain, problem, project)]",
    "what_q1_p3"    =   "1.1) What is it all about? [its main functionalities supported (e.g., modelling language, code generation, model analysis)]",
    "what_q1_p4"    =   "1.1) What is it all about? [the relation with its associated paper]",
    "what_q2_p1"    =   "1.2) What does it have? [a description of its directory structure and content]",
    "what_q2_p2"    =   "1.2) What does it have? [everything required for replications (i.e., complete)]",
    "what_q2_p3"    =   "1.2) What does it have? [no more assets than necessary for replications (i.e., concise)]",
    "what_q2_p4"    =   "1.2) What does it have? [a preprint of its associated article]",
    "what_q3_p1"    =   "1.3) What concepts and technologies underpin the artifact? [the theories that underpin its creation (e.g., formalisms, semantics)]",
    "what_q3_p2"    =   "1.3) What concepts and technologies underpin the artifact? [the modeling languages used to develop it (e.g., UML, xtUML, SysML, BPMN)]",
    "what_q3_p3"    =   "1.3) What concepts and technologies underpin the artifact? [the meta-modeling languages used to develop it (e.g., EMOF, CMOF, ECore/EMF, KM3)]",
    "what_q3_p4"    =   "1.3) What concepts and technologies underpin the artifact? [the standards and/or specifications used to develop it (e.g., ISO, CMI, XMI, CWM, HUTN, JMI, DD, OCL)]",
    "what_q3_p5"    =   "1.3) What concepts and technologies underpin the artifact? [the programming/markup language used to develop it]",
    "what_q3_p6"    =   "1.3) What concepts and technologies underpin the artifact? [the libraries, dependencies, and frameworks used to develop it and their respective versions (e.g., Eclipse release)]",
    "what_missing"  =   "Which factual questions would you say are missing in the What perspective?",
    "why_q1_p1" =   "2.1) Why it was created? [the motivation for its development]",
    "why_q1_p2" =   "2.1) Why it was created? [its objective/goal (e.g., verify claims, replicability, reusability, a whole new library/framework)]",
    "why_q1_p3" =   "2.1) Why it was created? [its advantages and/or novelty (e.g., algorithm, language, method)]",
    "why_missing"   =   "Which factual questions would you say are missing in the Why perspective?",
    "where_q1_p1"   =   "3.1) Where is it hosted? [is open and public (e.g., GitHub, BitBucket, Zenodo, Figshare)]",
    "where_q1_p2"   =   "3.1) Where is it hosted? [is indexed and findable by search engines (e.g., GitHub, BitBucket, Zenodo, Figshare)]",
    "where_q1_p3"   =   "3.1) Where is it hosted? [archives data for long-term and permanent access (e.g., Zenodo, Figshare)]",
    "where_q2_p1"   =   "3.2) Where shall I cite? [an explicit format for citation (e.g., in a CITATION file)]",
    "where_q2_p2"   =   "3.2) Where shall I cite? [its citation information in BibTeX format]",
    "where_q2_p3"   =   "3.2) Where shall I cite? [an URL for citation]",
    "where_q2_p4"   =   "3.2) Where shall I cite? [a DOI for citation]",
    "where_q3_p1"   =   "3.3) Where to find related work? [credit to data obtained from other sources (e.g., cited authors, paper, repository)]",
    "where_q3_p2"   =   "3.3) Where to find related work? [references about key concepts (e.g., papers, surveys, wiki, reports)]",
    "where_q3_p3"   =   "3.3) Where to find related work? [references to studies using it (e.g., known uses, integrated with)]",
    "where_q3_p4"   =   "3.3) Where to find related work? [references to related artifacts/projects]",
    "where_q3_p5"   =   "3.3) Where to find related work? [references using in-code citation (e.g., code header)]",
    "where_missing" =   "Which factual questions would you say are missing in the Where perspective?",
    "who_q1_p1" =   "4.1) Who could use it? [be deposited under an explicit open license (e.g., reported in a LICENSE file)]",
    "who_q1_p2" =   "4.1) Who could use it? [have files made available using open/non-proprietary formats (e.g., JSON, open XML schema)]",
    "who_q1_p3" =   "4.1) Who could use it? [indicate a list of potential users (e.g., professionals, researchers, industry sectors)]",
    "who_q1_p4" =   "4.1) Who could use it? [be developed using open, well-maintained, and documented libraries or dependencies]",
    "who_q2_p1" =   "4.2) Who are the authors? [a communication channel for interacting with the community (e.g., forum, mailing list, issue tracker, IRC, Slack, Discord)]",
    "who_q2_p2" =   "4.2) Who are the authors? [the names of its authors]",
    "who_q2_p3" =   "4.2) Who are the authors? [the institution of its authors]",
    "who_q2_p4" =   "4.2) Who are the authors? [the contact details of its authors (e.g., email address, ResearchGate, Linkedin, website)]",
    "who_q2_p5" =   "4.2) Who are the authors? [the ORCID of its authors]",
    "who_q2_p6" =   "4.2) Who are the authors? [the level of experience of its authors (e.g., bio, degree, position)]",
    "who_q3_p1" =   "4.3) Who funded this project? [the funding agencies that supported the project (e.g., ERC, NWO, CNPq, DFG, EPSRC, NSF)]",
    "who_missing"   =   "Which factual questions would you say are missing in the Who perspective?",
    "when_q1_p1"    =   "5.1) When did changes happen? [tracked using version control (e.g., GitHub, GitLab, BitBucket)]",
    "when_q1_p2"    =   "5.1) When did changes happen? [small (e.g., concise, cohesive edits)]",
    "when_q1_p3"    =   "5.1) When did changes happen? [explained (e.g., via CHANGELOG or commit messages)]",
    "when_q1_p4"    =   "5.1) When did changes happen? [labelled using tags and/or release identifiers to allow referencing and retrieval of specific versions]",
    "when_q2_p1"    =   "5.2) When do future changes shall happen? [a timeline for future goals and planned updates (e.g., frequency, next steps, future work plans)]",
    "when_q2_p2"    =   "5.2) When do future changes shall happen? [means for receiving change requests and feedback from users (e.g., bug fixes, pull requests)]",
    "when_missing"  =   "Which factual questions would you say are missing in the When perspective?",
    "how_q1_p1" =   "6.1) How is it organized? [Tabular data files shall follow analysis-friendly formats (e.g., the column is variable, the row is observation, data dictionary, the meaning of column/row headers)]",
    "how_q1_p2" =   "6.1) How is it organized? [Files and folders shall have self-explaining names matching content, meaning, and human abstractions (e.g., doc/, src/, results/, src/, bin/)]",
    "how_q1_p3" =   "6.1) How is it organized? [The artifact shall indicate best practices used (e.g., naming or code conventions, guidelines/checklists)]",
    "how_q1_p4" =   "6.1) How is it organized? [Useful metadata shall be used as part of filenames for pattern matching (e.g., yyyymmdd), where meaningful]",
    "how_q1_p5" =   "6.1) How is it organized? [The artifact shall be compliant with ICT accessibility standards (e.g., Section 508, WAI)]",
    "how_q1_p6" =   "6.1) How is it organized? [The experiment workflow shall be broken-down into small and simple procedures to facilitate reuse (e.g., scripts, functions)]",
    "how_q1_p7" =   "6.1) How is it organized? [The artifact shall include a website or wiki-page]",
    "how_q2_p1" =   "6.2) How to set up a running environment? [The artifact shall provide instructions for downloading]",
    "how_q2_p2" =   "6.2) How to set up a running environment? [The artifact shall provide the open-source code]",
    "how_q2_p3" =   "6.2) How to set up a running environment? [The artifact shall provide a binary/compiled version]",
    "how_q2_p4" =   "6.2) How to set up a running environment? [The artifact shall provide a container for freezing dependencies and quickly setting up a running environment (e.g., VM, Docker)]",
    "how_q2_p5" =   "6.2) How to set up a running environment? [The artifact shall provide a step-by-step tutorial of how to build the source code]",
    "how_q2_p6" =   "6.2) How to set up a running environment? [The artifact compilation shall rely on build automation tools (e.g., make, ant)]",
    "how_q2_p7" =   "6.2) How to set up a running environment? [The artifact compilation shall rely on dependency management tools (e.g., maven, pip)]",
    "how_q2_p8" =   "6.2) How to set up a running environment? [The artifact shall provide instructions to install it]",
    "how_q3_p1" =   "6.3) How to get started? [The artifact shall include instructions for running it on minimal test data (e.g., quick run, smoke testing)]",
    "how_q3_p2" =   "6.3) How to get started? [The artifact shall indicate the most relevant and interesting parts of the source code/artifact]",
    "how_q3_p3" =   "6.3) How to get started? [The artifact shall include step-by-step instructions for running it (e.g., README, PDF)]",
    "how_q3_p4" =   "6.3) How to get started? [The artifact shall include a video tutorial with the step-by-step for running it (e.g., Youtube, Vimeo)]",
    "how_q4_p1" =   "6.4) How to replicate the experiment? [The artifact shall include the complete set of test models considered]",
    "how_q4_p2" =   "6.4) How to replicate the experiment? [The artifact shall provide instructions for manual/automated pre-processing of raw data for experiments (e.g., bash, python, R script)]",
    "how_q4_p3" =   "6.4) How to replicate the experiment? [The artifact shall provide instructions for manual/automated replication of the complete (or at least a subset) experiment as in the paper (e.g., bash, python, R script)]",
    "how_q4_p4" =   "6.4) How to replicate the experiment? [The experiment workflow shall be fully automated (including raw data processing, experiment execution, figures plotting)]",
    "how_q4_p5" =   "6.4) How to replicate the experiment? [The artifact shall include the experiment results shown in its associated paper in tabular and machine-readable format (e.g., .csv, .tab)]",
    "how_q4_p6" =   "6.4) How to replicate the experiment? [The artifact shall include log files produced]",
    "how_q5_p1" =   "6.5) How to run the analysis of results? [The artifact shall provide scripts for the automated analysis of results as in the paper (e.g., R scripts, python scripts, Jupyter notebooks)]",
    "how_q5_p2" =   "6.5) How to run the analysis of results? [The artifact shall include scripts for drawing figures and/or plots as in the paper (e.g., R scripts, python scripts, Jupyter notebooks)]",
    "how_q5_p3" =   "6.5) How to run the analysis of results? [The artifact shall provide a clear description of the measurement procedures and metrics used in the paper]",
    "how_q6_p1" =   "6.6) How could it be repurposed? [The artifact shall indicate suggestions for contributions (e.g., notes.txt, todo.txt, ways it could be repurposed, wishlist)]",
    "how_q6_p2" =   "6.6) How could it be repurposed? [The artifact documentation shall be designed considering users with minimal expertise]",
    "how_q6_p3" =   "6.6) How could it be repurposed? [The artifact shall provide details about ethical concerns in replications]",
    "how_q6_p4" =   "6.6) How could it be repurposed? [The artifact source code shall be documented (e.g., in-code comments, Javadoc)]",
    "how_q6_p5" =   "6.6) How could it be repurposed? [The artifact shall provide instructions for integration/chaining with commercial tools (e.g., Matlab, DOORS)]",
    "how_q6_p6" =   "6.6) How could it be repurposed? [The artifact shall report known issues, bugs, and limitations (e.g., issue tracker)]",
    "how_missing"   =   "Which factual questions would you say are missing in the How perspective?",
    "howmuch_q1_p1" =   "7.1) How many resources does it need? [The artifact shall indicate the system and environment where it was successfully evaluated (e.g., OS, CPU, RAM, GPU, Disk)]",
    "howmuch_q1_p2" =   "7.1) How many resources does it need? [The artifact shall indicate the minimum system and environment requirements for usage (e.g., OS, CPU, RAM, GPU, Disk)]",
    "howmuch_q1_p3" =   "7.1) How many resources does it need? [The artifact shall indicate the skills and/or settings required for usage (e.g., team configuration, users' skills)]",
    "howmuch_q1_p4" =   "7.1) How many resources does it need? [The artifact shall indicate the approximate amount of time needed to replicate the experiment]",
    "howmuch_missing"   =   "Which factual questions would you say are missing in the How much/many perspective?",
    "clarity"   =   "How do you assess the clarity of these guidelines?",
    "completeness"  =   "How do you assess the completeness of these guidelines?",
    "relevance" =   "How do you assess the relevance of these guidelines?",
    "comments"  =   "Additional remarks"
  )
  return(keyval_survey)
}

survey_perspective <- c("what","what","what","what","what","what","what","what","what","what","what","what","what","what","why","why","why","where","where","where","where","where","where","where","where","where","where","where","where","who","who","who","who","who","who","who","who","who","who","who","when","when","when","when","when","when","how","how","how","how","how","how","how","how","how","how","how","how","how","how","how","how","how","how","how","how","how","how","how","how","how","how","how","how","how","how","how","how","how","how")
survey_levels <- factor(c('Unnecessary', 'Desirable', 'Essential'))