site_name: MDE Artifacts
site_url: https://mdeartifacts.github.io/
pages:
    - Home: index.md
    - The 5w2h method: intro5w2h.md
    - Guidelines for MDE artifacts: guidelines.md
    - Associated studies: relwork.md
    - FAQ: faq.md
theme: readthedocs