site_name: MDE Artifacts
site_url: https://mdeartifacts.github.io/
nav:
    - Home: index.md
    - The 5w2h: intro5w2h.md
    - Guidelines for MDE artifacts: guidelines.md
    - Related Work: relwork.md
    - Contact us: contactus.md
theme:
    name: 'cinder'